Code Revision #BroadcastReciever
elimu-ai/battery pull request #9
Opened 2017-01-09 18:08 UTC by adrygll2

2017-01-10 06:17 UTC, jo-elimu requested changes

2017-01-10 06:17 UTC, jogrimst commented on app/src/main/AndroidManifest.xml
> +                <action android:name="android.intent.action.BOOT_COMPLETED" />
Would it be better to listen for `android.intent.action.BATTERY_LOW` intents? - https://developer.android.com/training/monitoring-device-state/battery-monitoring.html

2017-01-10 06:17 UTC, jogrimst commented on app/src/main/java/org/literacyapp/battery/BatteryReciever.java
> +public class BatteryReciever extends BroadcastReceiver {
"Reciever" --> "Receiver"

2017-01-10 06:17 UTC, jogrimst commented on app/src/main/java/org/literacyapp/battery/BatteryReciever.java
> +        if(batteryPct == 99) {
Shouldn't this be something like `if (batteryPercentage < 10)` or `if (batteryPercentage < 5)`?

2017-01-10 10:49 UTC, adrygll2 commented on app/src/main/java/org/literacyapp/battery/BatteryReciever.java
> +        if(batteryPct == 99) {
Yes, but it's like this just for testing

2017-01-10 10:55 UTC, adrygll2 commented on app/src/main/java/org/literacyapp/battery/BatteryReciever.java
> +        if(batteryPct == 99) {
The onReceive method needs to be called from the main Activity?

2017-01-10 12:17 UTC, adrygll2 commented on app/src/main/java/org/literacyapp/battery/BatteryActivity.java
> +        intent.setAction("com.action.battery.notifier");
With this action now we can check the battery status and launch the activity.

2017-01-10 15:52 UTC, sladomic commented on app/src/main/java/org/literacyapp/battery/BatteryReceiver.java
> +        float batteryPct = level / (float)scale;
What if a value is empty (-1). Can this happen?

2017-01-10 17:24 UTC, adrygll2 commented on app/src/main/java/org/literacyapp/battery/BatteryReceiver.java
> +        float batteryPct = level / (float)scale;
@sladomic I tried with (0), but on the battery status is returning "NaN" and this cannot be use to calculate the percentage.
Battery level:: 0
Battery scale:: 0
Battery status:: NaN

With -1 value.

Battery level:: -1
Battery scale:: -1
Battery status:: 1.0

2017-01-10 17:37 UTC, adrygll2 commented on app/src/main/AndroidManifest.xml
> +                <action android:name="android.intent.action.BOOT_COMPLETED" />
@jogrimst I think with our own action intent, we can change the minimum battery status giving more time to connect the device isn't?

2017-01-13 14:33 UTC, jo-elimu requested changes
I don't understand what is triggering the detection of battery level. Is it an Intent broadcasted by the Android OS?

2017-01-13 14:33 UTC, jogrimst commented on app/src/main/AndroidManifest.xml
> +        android:fullBackupContent="true"
We are not integrated with Google Drive, so this line can be removed.

2017-01-13 14:33 UTC, jogrimst commented on app/src/main/AndroidManifest.xml
> +                <action android:name="android.intent.action.VIEW" />
Is the `android.intent.action.VIEW` intent necessary?

2017-01-13 14:33 UTC, jogrimst commented on app/src/main/java/org/literacyapp/battery/BatteryActivity.java
> +        intent.setAction("com.action.battery.notifier");
When is this Intent broadcasted?

2017-01-13 14:33 UTC, jogrimst commented on app/src/main/AndroidManifest.xml
> +                <action android:name="com.action.battery.notifier" />
Rename custom Intent to `literacyapp.intent.action.BATTERY_STATUS_CHANGED'

I'm assuming here that this intent is broadcasted every time the battery level changes. Is that correct?

2017-01-14 15:01 UTC, adrygll2 commented on app/src/main/AndroidManifest.xml
> +                <action android:name="com.action.battery.notifier" />
Yes, is exactly what you said.

2017-01-14 20:09 UTC, adrygll2 commented on app/src/main/java/org/literacyapp/battery/BatteryReceiver.java
> +        if(batteryPct <= 10 || batteryPct != 1.0) {
It checks 1.0 because when the device is connected battery status changes to that value.

2017-01-22 17:52 UTC, jo-elimu requested changes

2017-01-22 17:52 UTC, jogrimst commented on app/src/main/AndroidManifest.xml
> +    <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED" />
Why is `android.permission.RECEIVE_BOOT_COMPLETED` used?

2017-01-22 17:52 UTC, jogrimst commented on app/src/main/AndroidManifest.xml
> +                <action android:name="android.intent.action.BATTERY_LOW" />
If `literacyapp.intent.action.BATTERY_STATUS_CHANGED` is already being used, is `android.intent.action.BATTERY_LOW` and `android.intent.action.ACTION_POWER_CONNECTED` even necessary?

2017-01-22 17:52 UTC, jogrimst commented on app/src/main/java/org/literacyapp/battery/BatteryActivity.java
> +        sendBroadcast(intent);
The app should work without being opened, so delete this manual intent broadcast.

2017-01-22 17:52 UTC, jogrimst commented on app/src/main/java/org/literacyapp/battery/BatteryReceiver.java
> +        if(batteryPct <= 10 || batteryPct != 1.0) {
Will `|| batteryPct != 1.0` ever be executed?

2017-01-22 17:52 UTC, jogrimst commented on app/src/main/java/org/literacyapp/battery/BatteryActivity.java
>  public class BatteryActivity extends Activity {
Rename to `BatteryLowActivity` to indicate a little better the purpose of the activity.

2017-01-28 09:08 UTC, adrygll2 commented on app/src/main/java/org/literacyapp/battery/BatteryReceiver.java
> +        if(batteryPct <= 10 || batteryPct != 1.0) {
@jogrimst When the device is connected batteryPct changes to 1.0 and the activity is launch, so to ignore that I check this possibility.

2017-01-28 09:11 UTC, adrygll2 commented on app/src/main/AndroidManifest.xml
> +                <action android:name="android.intent.action.BATTERY_LOW" />
@jogrimst ok, I will remove all of them, they just were for testing.

2017-01-28 09:57 UTC, jogrimst commented on app/src/main/java/org/literacyapp/battery/BatteryReceiver.java
> +        if(batteryPct <= 10 || batteryPct != 1.0) {
@adrygll2 Is the percentage always equal to `1.0` when the device is charging?

2017-02-20 18:17 UTC, adrygll2 commented on app/src/main/java/org/literacyapp/battery/BatteryActivity.java
> +        sendBroadcast(intent);
@jogrimst But needs to be installed isn't?

2017-02-20 18:18 UTC, adrygll2 commented on app/src/main/java/org/literacyapp/battery/BatteryReceiver.java
> +        if(batteryPct <= 10 || batteryPct != 1.0) {
@jogrimst Yes, it is.

2017-02-20 18:31 UTC, adrygll2 commented on app/src/main/java/org/literacyapp/battery/BatteryActivity.java
> +        sendBroadcast(intent);
@jogrimst So, Should I move the code from BatteryReceiver to BatteryActivity?

2017-02-20 18:50 UTC, jogrimst commented on app/src/main/java/org/literacyapp/battery/BatteryReceiver.java
> +        if(batteryPct <= 10 || batteryPct != 1.0) {
The how is it possible to detect if the battery level is 1%?

2017-02-20 18:51 UTC, jogrimst commented on app/src/main/java/org/literacyapp/battery/BatteryActivity.java
> +        sendBroadcast(intent);
It depends on how often battery level changes are reported via Intents from the Android system. If it happens rarely, the best solution might be to create a background job running periodic checks.

2017-07-13 14:34 UTC, closed without merging